### ISSUE TITLE
Packagecontrol?

### ISSUE THREAD

**Issue by kapitanluffy** [sublimelsp/LSP-cspell#4]
Were you able to submit this to packagecontrol? I am trying to find it but it is not there.

**Comment by mauroreisvieira** [comment]
Hey @kapitanluffy you can add via:

<img width="727" alt="Screenshot 2023-03-03 at 9 47 45 AM" src="https://user-images.githubusercontent.com/3084774/222688101-be19406e-9340-4086-9023-c8938f1cec35.png">

After will be available to install, such as already in Package Control.

**Comment by kapitanluffy** [comment]
Yeah. I just wondered why not add it 😅

Anyway, I am already using it now. Awesome work!

**Comment by predragnikolic** [comment]
It is now available on PC
https://packagecontrol.io/packages/LSP-cspell
