### ISSUE TITLE
Unknown word different from highlighted mispelled word

### ISSUE THREAD

**Issue by kapitanluffy** [sublimelsp/LSP-cspell#5]
![image](https://user-images.githubusercontent.com/485799/224488284-33c1c84d-ab6c-4976-900a-41ac5496d7f1.png)

At the last line, I have `return sheets` but cspell is saying `sheetsimport`

**Comment by predragnikolic** [comment]
I will close this, because of:

> Looks like the servers got out of sync changes from the real document...

It doesn't look like a server issue, but rather as a LSP client issue.
If this issue happens again, feel free to open it at https://github.com/sublimelsp/LSP/issues
